export const API_SERVICE_URL = "https://cinesta.azurewebsites.net/api/v1/"
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SUBSCRIPTION_REQUEST = 'USER_SUBSCRIPTION_REQUEST'
export const USER_SUBSCRIPTION_SUCCESS = 'USER_SUBSCRIPTION_SUCCESS'
export const USER_SUBSCRIPTION_FAIL = 'USER_SUBSCRIPTION_FAIL'
export const USER_SUBSCRIPTION_DELETE = 'USER_SUBSCRIPTION_DELETE'

export const SUBSCRIPTION_REQUEST = 'SUBSCRIPTION_REQUEST'
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS'
export const SUBSCRIPTION_FAIL = 'SUBSCRIPTION_FAIL'
export const SUBSCRIPTION_DELETE = 'SUBSCRIPTION_DELETE'

export const PAYMENT_REQUEST = 'PAYMENT_REQUEST'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const PAYMENT_FAIL = 'PAYMENT_FAIL'
export const PAYMENT_DELETE = 'PAYMENT_DELETE'

export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAIL = 'PROFILE_FAIL'
export const PROFILE_DELETE = 'PROFILE_DELETE'
